Special game: Limited lives
1pulse/factorio_biter_battles pull request #327
Opened 2022-11-15 08:35 UTC by developer-8

This special game allows to set the maximum number of lives a player has per game. If a player dies more than the allowed number of lives, the player is sent to the island and can no longer participate in the game until the end of the game

The vote for this mode: https://discord.com/channels/823696400797138974/836401275645198357/880223970358607922

### Tested Changes:
- [x] I've tested the changes locally.

2022-11-16 20:26 UTC, TheBigZet reviewed
I guess if more and more events start using the `draw_text`, we'll have to think about a situation when more than one mode is played at once. (text overlapping)

2022-11-16 20:26 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +    local player = game.players[event.player_index]
```suggestion
    local player = game.get_player(event.player_index)
```

2022-11-16 20:26 UTC, TheBigZet commented on maps/biter_battles_v2/gui.lua
> +			if global.active_special_games["limited_lives"] and not global.special_games_variables["limited_lives"]['has_life'](player.name) then
Couldn't it just check `global.special_games_variables["limited_lives"]["player_lives"][player.name] > 0`? Without storing the function in global table

2022-11-17 03:08 UTC, developer-8 commented on maps/biter_battles_v2/gui.lua
> +			if global.active_special_games["limited_lives"] and not global.special_games_variables["limited_lives"]['has_life'](player.name) then
Also need to check for the existence of `global.special_games_variables["limited_lives"]["player_lives"][player.name]`, because if it is not exist, it means that the player has full lives. 
My intention was not to export the check logic outside of special game code, but if function in global variable is that bad, it can be done.

2022-11-17 06:26 UTC, TheBigZet commented on maps/biter_battles_v2/gui.lua
> +			if global.active_special_games["limited_lives"] and not global.special_games_variables["limited_lives"]['has_life'](player.name) then
No idea about the performance impact, but I guess you're right

2022-11-17 07:08 UTC, Ragnarok77-factorio requested changes
Tested it, worked OK otherwise

2022-11-17 07:08 UTC, Ragnarok77-factorio commented on comfy_panel/special_games.lua
> +		spectate(player)
Up to discussion but it would be nice if you got a player.print 'you have xx lives' left when you die and if it's != 0, just to remind players how many lives left they got

2022-11-17 07:11 UTC, Ragnarok77-factorio commented
> I guess if more and more events start using the `draw_text`, we'll have to think about a situation when more than one mode is played at once. (text overlapping)

Yes indeed

2022-11-17 08:17 UTC, developer-8 commented on comfy_panel/special_games.lua
> +		spectate(player)
I agree with your proposal. Added message for player

2022-11-17 09:36 UTC, Ragnarok77-factorio submitted a review, later dismissed
Ok for me now

2022-11-19 22:46 UTC, TheBigZet requested changes

2022-11-19 22:46 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	end
```suggestion
	global.active_special_games["limited_lives"] = true
	global.special_games_variables["limited_lives"] = {
		lives_limit = lives_limit,
		player_lives = {},
		has_life = function (player_name)
			local player_lives = global.special_games_variables["limited_lives"]["player_lives"][player_name]
			return player_lives == nil or player_lives > 0
		end
	}
```

2022-11-19 22:46 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +	if not global.active_special_games["limited_lives"] then return end
I wonder if `global.active_special_games.limited_lives` would be any faster

2022-11-19 22:46 UTC, TheBigZet commented on comfy_panel/special_games.lua
> +			table.concat({"You have ", player_lives , ((player_lives == 1) and "life" or "lives"), "left."}, " "),
I think it could print it when the player has no more lives left as well

2022-11-20 18:17 UTC, developer-8 commented on comfy_panel/special_games.lua
> +	if not global.active_special_games["limited_lives"] then return end
`To represent records, you use the field name as an index. Lua supports this representation by providing a.name as syntactic sugar for a["name"]`
`For Lua, the two forms are equivalent and can be intermixed freely; but for a human reader, each form may signal a different intention. `
https://www.lua.org/pil/2.5.html

I guess no difference in performance or its neglectable

2022-11-20 18:39 UTC, developer-8 commented on comfy_panel/special_games.lua
> +			table.concat({"You have ", player_lives , ((player_lives == 1) and "life" or "lives"), "left."}, " "),
Don't mind it, made a change

2022-11-21 10:47 UTC, TheBigZet approved these changes

2022-11-22 21:10 UTC, merged